import 'package:shadcn_flutter/shadcn_flutter.dart';

/// DeeMusiq brand theme — matches the website CSS at deemusiq-site/css/styles.css.
///
/// Dark, warm, honeycomb-glow aesthetic built from the site's CSS custom
/// properties. Applied as the DEFAULT theme when no accent color is selected,
/// and overrides the built-in "orange" scheme to use the brand orange.
///
/// Website color map:
///   --orange:    #FF5722   primary brand orange
///   --orange-2:  #FF7A45   lighter
///   --orange-3:  #FF9466   lightest
///   --gold:      #FFB300   accent gold
///   --ink:       #0c0a09   page background (darkest)
///   --ink-2:     #13100e
///   --surface:   #1a1512   card/panel bg
///   --surface-2: #221b16   hovered surface
///   --line:      rgba(255,120,60,.16)   border
///   --line-2:    rgba(255,255,255,.08)
///   --cream:     #f6efe9   primary text
///   --muted:     #a89c92   secondary text
///   --muted-2:   #7e736b   tertiary text
/// Curated accent colors offered in the picker, in display order.
///
/// Names are lowercase and must match `colorSchemeMap` keys: a name that has a
/// hand-tuned scheme in `colorSchemeMap` uses it; everything else (including
/// any user-typed hex) is generated by [DeeMusiqTheme.fromSeed].
class AccentPreset {
  final String name;
  final Color color;
  const AccentPreset(this.name, this.color);
}

const List<AccentPreset> accentPresets = <AccentPreset>[
  // Brand
  AccentPreset("deemusiq", DeeMusiqTheme.orange),
  AccentPreset("gold", DeeMusiqTheme.gold),
  // Hand-tuned shadcn schemes
  AccentPreset("slate", DeeMusiqTheme.slateSeed),
  AccentPreset("gray", DeeMusiqTheme.graySeed),
  AccentPreset("zinc", DeeMusiqTheme.zincSeed),
  AccentPreset("neutral", DeeMusiqTheme.neutralSeed),
  AccentPreset("stone", DeeMusiqTheme.stoneSeed),
  // Generated-from-seed accents
  AccentPreset("red", Color(0xFFE5484D)),
  AccentPreset("crimson", Color(0xFFC2323D)),
  AccentPreset("orange", DeeMusiqTheme.orange),
  AccentPreset("amber", Color(0xFFF59E0B)),
  AccentPreset("yellow", Color(0xFFEAB308)),
  AccentPreset("lime", Color(0xFFA3E635)),
  AccentPreset("green", Color(0xFF30A46C)),
  AccentPreset("emerald", Color(0xFF10B981)),
  AccentPreset("teal", Color(0xFF12A594)),
  AccentPreset("cyan", Color(0xFF3BC9DB)),
  AccentPreset("sky", Color(0xFF38BDF8)),
  AccentPreset("blue", Color(0xFF3B82F6)),
  AccentPreset("indigo", Color(0xFF6172F3)),
  AccentPreset("violet", Color(0xFF8E4EC6)),
  AccentPreset("purple", Color(0xFF9C6ADE)),
  AccentPreset("fuchsia", Color(0xFFD6409F)),
  AccentPreset("pink", Color(0xFFE93D82)),
  AccentPreset("rose", Color(0xFFF43F5E)),
  AccentPreset("bronze", Color(0xFFB07D62)),
];

class DeeMusiqTheme {
  DeeMusiqTheme._();

  // ── Seed colors for the hand-tuned LegacyColorSchemes ───────────────────
  static const Color slateSeed = Color(0xFF64748B);
  static const Color graySeed = Color(0xFF6B7280);
  static const Color zincSeed = Color(0xFF71717A);
  static const Color neutralSeed = Color(0xFF737373);
  static const Color stoneSeed = Color(0xFF78716C);


  // ── Brand colors ──────────────────────────────────────────────────────

  static const Color orange = Color(0xFFFF5722);
  static const Color orange2 = Color(0xFFFF7A45);
  static const Color orange3 = Color(0xFFFF9466);
  static const Color gold = Color(0xFFFFB300);
  static const Color ink = Color(0xFF0C0A09);
  static const Color ink2 = Color(0xFF13100E);
  static const Color surface = Color(0xFF1A1512);
  static const Color surface2 = Color(0xFF221B16);
  static const Color line = Color(0x29FF783C);   // rgba(255,120,60,.16)
  static const Color line2 = Color(0x14FFFFFF);   // rgba(255,255,255,.08)
  static const Color cream = Color(0xFFF6EFE9);
  static const Color muted = Color(0xFFA89C92);
  static const Color muted2 = Color(0xFF7E736B);

  // ── ShadcnFlutter ColorScheme ──────────────────────────────────────────

  /// Dark theme matching the DeeMusiq website.
  static ColorScheme dark() => const ColorScheme(
        brightness: Brightness.dark,
        background: ink,
        foreground: cream,
        primary: orange,
        primaryForeground: Color(0xFF1A0D06),
        secondary: orange2,
        secondaryForeground: cream,
        muted: surface,
        mutedForeground: muted,
        card: surface,
        cardForeground: cream,
        popover: surface2,
        popoverForeground: cream,
        border: line,
        input: surface2,
        accent: orange,
        accentForeground: Color(0xFF1A0D06),
        destructive: Color(0xFFEF4444),
        destructiveForeground: cream,
        ring: orange,
        chart1: orange,
        chart2: orange2,
        chart3: gold,
        chart4: orange3,
        chart5: cream,
        sidebar: ink2,
        sidebarForeground: muted,
        sidebarPrimary: orange,
        sidebarPrimaryForeground: Color(0xFF1A0D06),
        sidebarAccent: surface2,
        sidebarAccentForeground: cream,
        sidebarBorder: line,
        sidebarRing: orange,
      );

  /// Light theme (rarely used — DeeMusiq is dark-first). Keeps the brand
  /// orange but on a warm cream background.
  static ColorScheme light() => const ColorScheme(
        brightness: Brightness.light,
        background: cream,
        foreground: ink,
        primary: orange,
        primaryForeground: Colors.white,
        secondary: orange2,
        secondaryForeground: ink,
        muted: Color(0xFFF0EAE4),
        mutedForeground: muted2,
        card: Colors.white,
        cardForeground: ink,
        popover: Colors.white,
        popoverForeground: ink,
        border: Color(0x20FF783C),
        input: Color(0xFFF0EAE4),
        accent: orange,
        accentForeground: Colors.white,
        destructive: Color(0xFFEF4444),
        destructiveForeground: Colors.white,
        ring: orange,
        chart1: orange,
        chart2: orange2,
        chart3: gold,
        chart4: orange3,
        chart5: ink,
        sidebar: Color(0xFFF0EAE4),
        sidebarForeground: muted2,
        sidebarPrimary: orange,
        sidebarPrimaryForeground: Colors.white,
        sidebarAccent: Color(0xFFF0EAE4),
        sidebarAccentForeground: ink,
        sidebarBorder: Color(0x20FF783C),
        sidebarRing: orange,
      );

  // ── Theme builders (match ShadcnFlutter's LegacyColorSchemes pattern) ──

  /// Returns the appropriate ColorScheme for the given [ThemeMode].
  static ColorScheme forMode(ThemeMode mode) =>
      mode == ThemeMode.light ? light() : dark();

  /// Legacy-style factory matching `LegacyColorSchemes.orange` signature,
  /// so it can be dropped into `colorSchemeMap` without changing callers.
  static ColorScheme Function(ThemeMode) get schemeFactory =>
      (ThemeMode mode) => forMode(mode);
}

/// Extension that injects the DeeMusiq theme as the default in the
/// `colorSchemeMap` used by [main.dart]. Call once during app init.
void registerDeeMusiqTheme(Map<String, ColorScheme Function(ThemeMode)> map) {
  // Override the built-in "orange" scheme with the brand orange.
  map['orange'] = DeeMusiqTheme.schemeFactory;
  // Add a dedicated "deemusiq" key for the full website-matched theme.
  map['deemusiq'] = DeeMusiqTheme.schemeFactory;
}
